

const Hero = () => {
  return (
    <>
      <div className='hero bg-gray-100 h-[100vh] w-full' >
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
        <p>lorem30</p>
      </div>
    </>
  )
}

export default Hero
